// Code generated by "stringer -type ErrorType -linecomment"; DO NOT EDIT.

package errors

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoType-0]
	_ = x[BadRequest-1]
	_ = x[NotFound-2]
}

const _ErrorType_name = "未知异常请求错误没有资源"

var _ErrorType_index = [...]uint8{0, 12, 24, 36}

func (i ErrorType) String() string {
	if i >= ErrorType(len(_ErrorType_index)-1) {
		return "ErrorType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
