// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package error_handle

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ServerError-10101]
	_ = x[TooManyRequests-10102]
	_ = x[ParamBindError-10103]
	_ = x[AuthorizationError-10104]
	_ = x[CallHTTPError-10105]
	_ = x[ResubmitError-10106]
	_ = x[ResubmitMsg-10107]
	_ = x[HashIdsDecodeError-10108]
	_ = x[SignatureError-10109]
}

const _ErrCode_name = "Internal Server ErrorToo Many Requests参数信息有误签名信息有误调用第三方HTTP接口失败ResubmitError请勿重复提交ID参数有误SignatureError"

var _ErrCode_index = [...]uint8{0, 21, 38, 56, 74, 105, 118, 136, 150, 164}

func (i ErrCode) String() string {
	i -= 10101
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i+10101), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
